spring:
  application:
    name: knowledge-hub-api

  datasource:
    url: jdbc:postgresql://localhost:5432/knowledge_hub
    username: postgres
    password: 888888
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        max-page-size: 100
    redis:
      host: localhost
      port: 6378
      password: 123456

jwt:
  secret: knowledge-hub-local-jwt-signing-key-for-course-2026
  expiration: 7200000

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
