spring:
  application:
    name: knowledge-hub-api

  datasource:
    url: jdbc:postgresql://localhost:5432/knowledge_hub
    username: postgres
    password: 888888
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
    redis:
      host: localhost
      port: 6378
      password: 123456

jwt:
  secret: knowledge-hub-local-jwt-signing-key-for-course-2026
  expiration: 7200000

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: knowledge-hub

cache:
  detail-ttl: 30m

server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{traceId:-no-trace}] [%thread] %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: debug
